### ISSUE TITLE
the middleware is not upstream

### ISSUE THREAD

**Issue by EmilienM** [pandemicsyn/swift-informant#17]
Why not moving the middleware to openstack/swift?

https://github.com/openstack/swift/tree/master/swift/common/middleware

**Comment by guimaluf** [comment]
:+1:

**Comment by pandemicsyn** [comment]
Swift itself actually includes statsd middleware (imho its a bit verbose for the backend's but the proxy version is ok). http://docs.openstack.org/developer/swift/admin_guide.html#reporting-metrics-to-statsd
