### ISSUE TITLE
Swift proxy with apache mod_wsgi informant doesn't work

### ISSUE THREAD

**Issue by cmarodrigues** [pandemicsyn/swift-informant#18]
Hi,

I have Swift proxy server send stats to statsd using informant middle
ware, and when run this from proxy-server daemon, the statsd receive
information correctly, but when i move proxy-server to apache+mod_wsgi,
the stastd stop to receive information.

Any one knows any issue with mod_wsgi and informant? 

Regards,
## 

Carlos Rodrigues

**Comment by pandemicsyn** [comment]
Sorry, no idea as I've never run the swift services via Apache (and sorta think thats a terrible idea to be honest).
